#!/usr/bin/env python3
"""Independent reference implementation of the fair-compute workload.

This exists for exactly one reason: to generate known-answer test vectors from
an implementation that shares no code with the Rust version. If the Rust and
this file agree, the odds that both contain the same transcription error are
low. If they disagree, one of them is wrong and the KAT test says so.

Written to mirror the Rust source line-for-line, deliberately unoptimised.
Do not "clean this up" -- its value is in being a separate transcription.
"""

M64 = (1 << 64) - 1


def mix(x):
    z = (x + 0x9E3779B97F4A7C15) & M64
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & M64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & M64
    return (z ^ (z >> 31)) & M64


def init_scratchpad(words, seed):
    return [mix(seed ^ ((i * 0x10000000000001B3) & M64)) for i in range(words)]


def run_chain(pad, seed, words, steps):
    mask = words - 1
    acc = mix(seed ^ 0xA5A55A5AC3C33C3C)
    for step in range(steps):
        idx = acc & mask
        v = pad[idx]
        acc = (mix(acc ^ v) + step) & M64
        pad[idx] = v ^ acc
    return acc


def finalize(pad, acc, seed, words, steps):
    h0 = mix(acc)
    h1 = mix(acc ^ steps)
    h2 = mix(acc ^ words)
    h3 = mix(acc ^ seed)

    SAMPLES = 1024
    stride = words // SAMPLES if words > SAMPLES else 1

    i = 0
    while i < words:
        v = pad[i]
        h0 = mix(h0 ^ v)
        h1 = (h1 + mix(v ^ i)) & M64
        h2 ^= mix(h2 ^ v)
        h3 = mix((h3 + v) & M64)
        i += stride

    return [h0, h1, h2, h3]


def execute(seed, words, steps):
    pad = init_scratchpad(words, seed)
    acc = run_chain(pad, seed, words, steps)
    return finalize(pad, acc, seed, words, steps)


def to_hex(digest):
    return "".join("%016x" % w for w in digest)


VECTORS = [
    (0, 1024, 10_000),
    (0, 1024, 10_001),
    (1, 1024, 10_000),
    (0xDEADBEEFCAFEF00D, 4096, 100_000),
    (0x0123456789ABCDEF, 65536, 250_000),
]

if __name__ == "__main__":
    print("// Generated by reference/reference_workload.py -- do not hand-edit.")
    for seed, words, steps in VECTORS:
        d = execute(seed, words, steps)
        print("KAT seed=0x%016x words=%d steps=%d -> %s" % (seed, words, steps, to_hex(d)))
